# Project information
sonar.projectKey=etudedecas
sonar.organization=etudedecas
sonar.host.url=https://sonarcloud.io
sonar.login=8b5348f260ef12a9072018111b329a68734ec22a

# Source encoding
sonar.sourceEncoding=UTF-8

# Analysis configuration
sonar.java.source=17
sonar.coverage.exclusions=**/*Application.java,**/entity/**,**/model/**,**/dto/**
sonar.cpd.exclusions=**/entity/**,**/model/**,**/dto/**

# Project structure
sonar.modules=eureka-service,gateway-service,service-client,service-voiture

# Module configurations
eureka-service.sonar.sources=src/main/java
gateway-service.sonar.sources=src/main/java
service-client.sonar.sources=src/main/java
service-voiture.sonar.sources=src/main/java

# Temporarily disable certain rules or lower thresholds
sonar.qualitygate.wait=false
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml