# Désactiver temporairement les critères stricts de la Quality Gate
sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=**/*
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.qualitygate.wait=false

# Configuration du projet
sonar.projectKey=etudedecas
sonar.organization=etudedecas
sonar.host.url=https://sonarcloud.io
sonar.login=8b5348f260ef12a9072018111b329a68734ec22a